target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # 👇 Force-include only the necessary iOS SDKs
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Google-Mobile-Ads-SDK'
end
